# Generated by Django 6.0.3 on 2026-04-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.CharField(blank=True, default='avatar1', help_text='Nombre del avatar predeterminado', max_length=50, null=True),
        ),
    ]
