# Generated by Django 6.0.3 on 2026-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueparticipant',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
